export default {
    'GET_RECIPES': 'GET_RECIPES',
    'GET_RECIPES_SUCCESS': 'GET_RECIPES_SUCCESS',
    'GET_RECIPES_ERROR': 'GET_RECIPES_ERROR',
  
    //chef
    'GET_CHEFS': 'GET_CHEFS',
    'GET_CHEFS_SUCCESS': 'GET_CHEFS_SUCCESS',
    'GET_CHEFS_ERROR': 'GET_CHEFS_ERROR',

    //galeria
    'GET_GALERIAFOTOS': 'GET_GALERIAFOTOS',
    'GET_GALERIAFOTOS_SUCCESS': 'GET_GALERIAFOTOS_SUCCESS',
    'GET_GALERIAFOTOS_ERROR': 'GET_GALERIAFOTOS_ERROR',

  }